import {FrameworkConfiguration, PLATFORM} from "aurelia-framework";

export function configure(config: FrameworkConfiguration) {
    config.globalResources([
        // Custom Elements
        // ---------------------------------------------------------------
        PLATFORM.moduleName('./elements/authenticated/account/account-list'),
        PLATFORM.moduleName('./elements/authenticated/account/account-list-item'),
        PLATFORM.moduleName('./elements/authenticated/account/account-statements'),
        PLATFORM.moduleName('./elements/authenticated/account/account-transactions'),
        PLATFORM.moduleName('./elements/authenticated/account/accounts'),
        PLATFORM.moduleName('./elements/authenticated/account/spending-activity'),
        PLATFORM.moduleName('./elements/authenticated/csv/csv-viewer'),
        PLATFORM.moduleName('./elements/authenticated/document/document-uploader'),
        PLATFORM.moduleName('./elements/authenticated/document/document-viewer'),
        PLATFORM.moduleName('./elements/authenticated/mailbox/conversations'),
        PLATFORM.moduleName('./elements/authenticated/mailbox/mailbox'),
        PLATFORM.moduleName('./elements/authenticated/mailbox/messages'),
        PLATFORM.moduleName('./elements/authenticated/mailbox/new-conversation'),
        PLATFORM.moduleName('./elements/authenticated/mailbox/subjects'),
        PLATFORM.moduleName('./elements/authenticated/manage/authenticator/authenticator-devices'),
        PLATFORM.moduleName('./elements/authenticated/manage/authenticator/authenticator-enroll'),
        PLATFORM.moduleName('./elements/authenticated/manage/authenticator/manage-authenticator'),
        PLATFORM.moduleName('./elements/authenticated/manage/mfa/manage-mfa'),
        PLATFORM.moduleName('./elements/authenticated/manage/notifications/business-notifications-editor'),
        PLATFORM.moduleName('./elements/authenticated/manage/notifications/customer-notifications-editor'),
        PLATFORM.moduleName('./elements/authenticated/manage/notifications/manage-business-notifications'),
        PLATFORM.moduleName('./elements/authenticated/manage/notifications/manage-customer-notifications'),
        PLATFORM.moduleName('./elements/authenticated/manage/password/manage-password'),
        PLATFORM.moduleName('./elements/authenticated/manage/permissions/corporate-structure'),
        PLATFORM.moduleName('./elements/authenticated/manage/permissions/manage-permissions'),
        PLATFORM.moduleName('./elements/authenticated/manage/permissions/member-permissions'),
        PLATFORM.moduleName('./elements/authenticated/manage/pki/generate-digital-certificates'),
        PLATFORM.moduleName('./elements/authenticated/manage/pki/list-digital-certificates'),
        PLATFORM.moduleName('./elements/authenticated/manage/pki/manage-digital-certificates'),
        PLATFORM.moduleName('./elements/authenticated/manage/requests/manage-requests'),
        PLATFORM.moduleName('./elements/authenticated/manage/requests/request-detail'),
        PLATFORM.moduleName('./elements/authenticated/manage/sms/manage-sms'),
        PLATFORM.moduleName('./elements/authenticated/manage/webhooks/add-webhook'),
        PLATFORM.moduleName('./elements/authenticated/manage/webhooks/edit-webhook'),
        PLATFORM.moduleName('./elements/authenticated/manage/webhooks/manage-webhooks'),
        PLATFORM.moduleName('./elements/authenticated/manage/webhooks/view-webhook'),
        PLATFORM.moduleName('./elements/authenticated/manage/webhooks/webhooks'),
        PLATFORM.moduleName('./elements/authenticated/payments/authorize/authorize-bulk-payment-detail'),
        PLATFORM.moduleName('./elements/authenticated/payments/authorize/authorize-payment-detail'),
        PLATFORM.moduleName('./elements/authenticated/payments/authorize/payment-authorize'),
        PLATFORM.moduleName('./elements/authenticated/payments/beneficiaries/add-beneficiary'),
        PLATFORM.moduleName('./elements/authenticated/payments/beneficiaries/bulk/beneficiary-bulk'),
        PLATFORM.moduleName('./elements/authenticated/payments/beneficiaries/edit-beneficiary'),
        PLATFORM.moduleName('./elements/authenticated/payments/beneficiaries/link-beneficiary'),
        PLATFORM.moduleName('./elements/authenticated/payments/beneficiaries/manage-beneficiaries'),
        PLATFORM.moduleName('./elements/authenticated/payments/beneficiaries/payment-beneficiaries'),
        PLATFORM.moduleName('./elements/authenticated/payments/beneficiaries/view-beneficiary'),
        PLATFORM.moduleName('./elements/authenticated/payments/beneficiaries/view-beneficiary-documents'),
        PLATFORM.moduleName('./elements/authenticated/payments/orders/payment-detail'),
        PLATFORM.moduleName('./elements/authenticated/payments/orders/payment-orders'),
        PLATFORM.moduleName('./elements/authenticated/payments/send/bulk/payment-bulk'),
        PLATFORM.moduleName('./elements/authenticated/payments/send/payment-send'),
        PLATFORM.moduleName('./elements/authenticated/payments/transfer/payment-transfer'),

        // @Leonid:  You can add your custom elements below here
        PLATFORM.moduleName('./elements/authenticated/risk/bwra-profile-manager'),
        PLATFORM.moduleName('./elements/authenticated/risk/cra-profile-manager'),
        PLATFORM.moduleName('./elements/authenticated/risk/risk-config'),
        PLATFORM.moduleName('./elements/authenticated/risk/risk-landing'),
        PLATFORM.moduleName('./elements/authenticated/risk/risk-list-manager'),
        PLATFORM.moduleName('./elements/authenticated/risk/risk-profile-manager'),

        // Legacy to remove
        PLATFORM.moduleName("./elements/components/cra/cra-risk-factor"),
        // @Leonid:  You can add your custom elements above here

        PLATFORM.moduleName('./elements/components/grid/grid-box-items'),
        PLATFORM.moduleName('./elements/components/grid/grid-item-box'),
        PLATFORM.moduleName('./elements/components/site/banner-notifications/banner-notifications'),
        PLATFORM.moduleName('./elements/date/date-picker'),
        PLATFORM.moduleName('./elements/dropzone/document-dropzone'),
        PLATFORM.moduleName('./elements/system/maintenance'),
        PLATFORM.moduleName('./elements/transactions/pending-transaction-message'),
        PLATFORM.moduleName('./elements/transactions/pending-transaction-messages'),
        PLATFORM.moduleName('./elements/transactions/pending-transaction-modal'),

        PLATFORM.moduleName('./elements/job/job-viewer'),
        PLATFORM.moduleName('./elements/unauthenticated/auth/login-mfa'),
        PLATFORM.moduleName('./elements/transactions/gps-transaction-row'),
        PLATFORM.moduleName('./elements/transactions/gps-transaction-detail'),
        PLATFORM.moduleName('./elements/transactions/clearbank-transaction-detail'),

        PLATFORM.moduleName("./elements/mfa/mfa-info"),
        PLATFORM.moduleName("./elements/mfa/mfa-setup"),
        PLATFORM.moduleName("./elements/mfa/mfa-totp"),

        PLATFORM.moduleName("./elements/authenticated/customer/customer"),
        PLATFORM.moduleName("./elements/authenticated/dashboard"),
        PLATFORM.moduleName("./elements/unauthenticated/registration/finish-registration"),
        PLATFORM.moduleName("./elements/unauthenticated/registration/start-registration"),
        PLATFORM.moduleName("./elements/unauthenticated/registration/confirm-registration"),
        PLATFORM.moduleName("./elements/unauthenticated/registration/finish-registration"),

        PLATFORM.moduleName("./elements/unauthenticated/auth/login"),
        PLATFORM.moduleName("./elements/components/site/header/header"),
        PLATFORM.moduleName("./elements/components/site/header/header-logo"),
        PLATFORM.moduleName("./elements/components/site/form/form-group"),
        PLATFORM.moduleName("./elements/components/site/footer/site-footer"),
        PLATFORM.moduleName("./elements/components/site/footer/footer"),
        PLATFORM.moduleName("./elements/components/site/footer/footer-items"),
        PLATFORM.moduleName("./elements/components/site/footer/footer-item"),
        PLATFORM.moduleName("./elements/components/site/footer/footer-copyright"),
        PLATFORM.moduleName("./elements/components/site/navbar/navbar"),
        PLATFORM.moduleName("./elements/components/site/navbar/navbar-items"),
        PLATFORM.moduleName("./elements/components/site/navbar/navbar-item"),
        PLATFORM.moduleName("./elements/components/site/content/page-content"),
        PLATFORM.moduleName("./elements/components/site/content/content-tile"),
        PLATFORM.moduleName("./elements/components/site/content/content-container"),
        PLATFORM.moduleName("./elements/components/site/content/content-column"),
        PLATFORM.moduleName("./elements/components/auth/signup-panel"),
        PLATFORM.moduleName("./elements/components/auth/login-panel"),
        PLATFORM.moduleName("./elements/components/auth/login-container"),
        PLATFORM.moduleName("./elements/components/site/header/site-header"),
        PLATFORM.moduleName("./elements/components/site/loading-indicator"),

        PLATFORM.moduleName("./elements/components/kendo/kendo-money-input"),
        PLATFORM.moduleName("./elements/components/kendo/kendo-drop-down-list"),
        PLATFORM.moduleName("./elements/components/kendo/kendo-masked-text-box"),
        PLATFORM.moduleName("./elements/components/kendo/kendo-date-picker"),



        PLATFORM.moduleName('./elements/unauthenticated/auth/start-password-reset'),
        PLATFORM.moduleName('./elements/unauthenticated/auth/confirm-password-reset'),
        PLATFORM.moduleName('./elements/unauthenticated/auth/finish-password-reset'),
        PLATFORM.moduleName("./elements/unauthenticated/auth/change-password"),

        // Custom Attributes
        // ---------------------------------------------------------------
        PLATFORM.moduleName('./attributes/on-hover'),
        PLATFORM.moduleName("./attributes/change-case"),
        PLATFORM.moduleName("./attributes/disable-while-loading"),
        PLATFORM.moduleName("./attributes/intl-tel"),
        PLATFORM.moduleName("./attributes/number-input"),
        PLATFORM.moduleName("./attributes/on-enter"),
        PLATFORM.moduleName("./attributes/hover-css"),

        // Binding Behaviors
        // ---------------------------------------------------------------

        // Value Converters
        // ---------------------------------------------------------------
        PLATFORM.moduleName('./value-converters/acl-sort'),
        PLATFORM.moduleName('./value-converters/currency-format'),
        PLATFORM.moduleName('./value-converters/date-format'),
        PLATFORM.moduleName('./value-converters/epoch-format'),
        PLATFORM.moduleName('./value-converters/file-size'),
        PLATFORM.moduleName('./value-converters/filter-hidden'),
        PLATFORM.moduleName('./value-converters/filter-mailbox'),
        PLATFORM.moduleName('./value-converters/filter-notifications'),
        PLATFORM.moduleName('./value-converters/filter-on-business-manager'),
        PLATFORM.moduleName('./value-converters/filter-on-property'),
        PLATFORM.moduleName('./value-converters/friendly-acl'),
        PLATFORM.moduleName('./value-converters/friendly-ern'),
        PLATFORM.moduleName('./value-converters/humanize'),
        PLATFORM.moduleName('./value-converters/route-filter'),
        PLATFORM.moduleName('./value-converters/scheme-format'),
        PLATFORM.moduleName('./value-converters/sort-value-converter'),
    ]);
}
