version: "3.7"

services:
  online-account:
    image: online-account:0.1.0
    build:
      context: . # relative to docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    restart: unless-stopped
